app_engine_apis: true
runtime: python311
instance_class: F1
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
# expiration time for static files
default_expiration: "7d"

handlers:
# this is only used for the development environment if a CDN is not set up
- url: /static
  static_dir: static

- url: /.*
  script: auto
  login: admin
  secure: always

# FIXME fill environment variables
env_variables:
  SECRET_KEY: ''            # a random secret phrase used for flask sessions
  PROJECT: ''               # google cloud project to monitor
  DOMAIN: ''                # your domain name, e.g. example.com
  CDN: ''                   # your cdn url for static files

inbound_services:
- warmup
